### ISSUE TITLE
Option to use ReadGeoData on files without an AREA column

### ISSUE THREAD

**Issue by dgustafsson** [rcapell/RHYPE#44]
I am using ReadGeoData to read other HYPE input files with similar structure, such as GlacierData, or a previously calculated and saved upstreamgeodata. Now, this does not work anymore, since ReadGeoData requires and AREA column. Of course I could use ReadLakeData, but it would maybe be better to eitehr have an option to switch of the AREA requirement in ReadGeoData, or to have a general function to read the HYPE input tables with this structure?

**Comment by rcapell** [comment]
Do you use the latest development version (not the latest release), installed with devtools? Import works for me with that, I made a change in the import function recently because i had the same problem.

I will add a ReadGlacierData() function nonetheless, just for completeness, I prefer that to having a generic import function with input-dependent behaviour.

**Comment by rcapell** [comment]
Tested ReadGeoData() once more without area column, works here. 
Closing.
